package com.ecart.model;
// Generated Apr 20, 2016 1:35:56 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cartitems generated by hbm2java
 */
@Entity
@Table(name = "cartitems", catalog = "ecart_schema", uniqueConstraints = @UniqueConstraint(columnNames = "item_imageUrl"))
public class Cartitems implements java.io.Serializable {

	private Integer itemId;
	private String itemName;
	private String itemPrice;
	private String itemImageUrl;
	private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

	public Cartitems() {
	}

	public Cartitems(String itemName, String itemPrice, String itemImageUrl) {
		this.itemName = itemName;
		this.itemPrice = itemPrice;
		this.itemImageUrl = itemImageUrl;
	}

	public Cartitems(String itemName, String itemPrice, String itemImageUrl, Set<OrderDetails> orderDetailses) {
		this.itemName = itemName;
		this.itemPrice = itemPrice;
		this.itemImageUrl = itemImageUrl;
		this.orderDetailses = orderDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "item_Id", unique = true, nullable = false)
	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	@Column(name = "item_name", nullable = false, length = 15)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "item_price", nullable = false, length = 5)
	public String getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(String itemPrice) {
		this.itemPrice = itemPrice;
	}

	@Column(name = "item_imageUrl", unique = true, nullable = false)
	public String getItemImageUrl() {
		return this.itemImageUrl;
	}

	public void setItemImageUrl(String itemImageUrl) {
		this.itemImageUrl = itemImageUrl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cartitems")
	public Set<OrderDetails> getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
