package com.ecart.model;
// Generated Apr 20, 2016 1:35:56 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LoginDetails generated by hbm2java
 */
@Entity
@Table(name = "login_details", catalog = "ecart_schema", uniqueConstraints = @UniqueConstraint(columnNames = "login_password"))
public class LoginDetails implements java.io.Serializable {

	private String loginId;
	private String loginPassword;
	private String fullName;
	private int contact;
	private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

	public LoginDetails() {
	}

	public LoginDetails(String loginId, String loginPassword, String fullName, int contact) {
		this.loginId = loginId;
		this.loginPassword = loginPassword;
		this.fullName = fullName;
		this.contact = contact;
	}

	public LoginDetails(String loginId, String loginPassword, String fullName, int contact,
			Set<OrderDetails> orderDetailses) {
		this.loginId = loginId;
		this.loginPassword = loginPassword;
		this.fullName = fullName;
		this.contact = contact;
		this.orderDetailses = orderDetailses;
	}

	@Id

	@Column(name = "login_id", unique = true, nullable = false, length = 10)
	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	@Column(name = "login_password", unique = true, nullable = false, length = 45)
	public String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	@Column(name = "full_name", nullable = false, length = 45)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "contact", nullable = false)
	public int getContact() {
		return this.contact;
	}

	public void setContact(int contact) {
		this.contact = contact;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loginDetails")
	public Set<OrderDetails> getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
