package com.ecart.model;
// Generated Apr 20, 2016 1:35:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderDetailsId generated by hbm2java
 */
@Embeddable
public class OrderDetailsId implements java.io.Serializable {

	private String userId;
	private int itemId;
	private Integer quantity;
	private String itemPrice;

	public OrderDetailsId() {
	}

	public OrderDetailsId(String userId, int itemId) {
		this.userId = userId;
		this.itemId = itemId;
	}

	public OrderDetailsId(String userId, int itemId, Integer quantity, String itemPrice) {
		this.userId = userId;
		this.itemId = itemId;
		this.quantity = quantity;
		this.itemPrice = itemPrice;
	}

	@Column(name = "user_id", nullable = false, length = 10)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "item_id", nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "item_price", length = 5)
	public String getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(String itemPrice) {
		this.itemPrice = itemPrice;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDetailsId))
			return false;
		OrderDetailsId castOther = (OrderDetailsId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& (this.getItemId() == castOther.getItemId())
				&& ((this.getQuantity() == castOther.getQuantity()) || (this.getQuantity() != null
						&& castOther.getQuantity() != null && this.getQuantity().equals(castOther.getQuantity())))
				&& ((this.getItemPrice() == castOther.getItemPrice()) || (this.getItemPrice() != null
						&& castOther.getItemPrice() != null && this.getItemPrice().equals(castOther.getItemPrice())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + this.getItemId();
		result = 37 * result + (getQuantity() == null ? 0 : this.getQuantity().hashCode());
		result = 37 * result + (getItemPrice() == null ? 0 : this.getItemPrice().hashCode());
		return result;
	}

}
