package com.ecart.model;
// Generated Apr 20, 2016 1:35:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name = "order_details", catalog = "ecart_schema")
public class OrderDetails implements java.io.Serializable {

	private OrderDetailsId id;
	private Cartitems cartitems;
	private LoginDetails loginDetails;

	public OrderDetails() {
	}

	public OrderDetails(OrderDetailsId id, Cartitems cartitems, LoginDetails loginDetails) {
		this.id = id;
		this.cartitems = cartitems;
		this.loginDetails = loginDetails;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 10)),
			@AttributeOverride(name = "itemId", column = @Column(name = "item_id", nullable = false)),
			@AttributeOverride(name = "quantity", column = @Column(name = "quantity")),
			@AttributeOverride(name = "itemPrice", column = @Column(name = "item_price", length = 5)) })
	public OrderDetailsId getId() {
		return this.id;
	}

	public void setId(OrderDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id", nullable = false, insertable = false, updatable = false)
	public Cartitems getCartitems() {
		return this.cartitems;
	}

	public void setCartitems(Cartitems cartitems) {
		this.cartitems = cartitems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public LoginDetails getLoginDetails() {
		return this.loginDetails;
	}

	public void setLoginDetails(LoginDetails loginDetails) {
		this.loginDetails = loginDetails;
	}

}
